name: tests
on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project...
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Installing pnpm
        run: npm install pnpm -g
      - name: Installing all dependencies
        run: pnpm install
      - name: Running tests...
        run: pnpm run test